# My Rules
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
WPM_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BLUETOOTH_ENABLE = no
HD44780_ENABLE = no
BACKLIGHT_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
